# Generated by Django 4.2.2 on 2023-07-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject_key', models.IntegerField()),
                ('year', models.CharField(max_length=30, null=True)),
                ('semester', models.CharField(max_length=30, null=True)),
                ('credits', models.FloatField(null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('coordinator', models.CharField(max_length=255, null=True)),
                ('previous_requirements', models.TextField(null=True)),
                ('subject_url', models.URLField(null=True)),
                ('content', models.TextField(null=True)),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.degree')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.university')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.university'),
        ),
    ]
