# Generated by Django 4.2.2 on 2023-09-21 14:52

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10000)),
                ('subject_key', models.IntegerField()),
                ('year', models.TextField(max_length=30, null=True)),
                ('semester', models.TextField(max_length=30, null=True)),
                ('credits', models.FloatField(null=True)),
                ('language', models.TextField(max_length=10000, null=True)),
                ('coordinator', models.TextField(max_length=10000, null=True)),
                ('previous_requirements', models.TextField(null=True)),
                ('subject_url', models.URLField(null=True)),
                ('content', models.TextField(null=True)),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.degree')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_file_uab', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uab/', location='C:\\Users\\Pablo\\OneDrive\\Documentos\\1Programacion\\TFG\\subjects/Data/iCalendar/UAB'), upload_to='')),
                ('schedule_file_uam', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uam/', location='C:\\Users\\Pablo\\OneDrive\\Documentos\\1Programacion\\TFG\\subjects/Data/iCalendar/UAM'), upload_to='')),
                ('schedule_file_uc3m', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uc3m/', location='C:\\Users\\Pablo\\OneDrive\\Documentos\\1Programacion\\TFG\\subjects/Data/iCalendar/UC3M'), upload_to='')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 21, 16, 52, 45, 978284))),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('Apuntes', 'Apuntes'), ('Ejercicios', 'Ejercicios'), ('Examenes', 'Exámenes')], default='Apuntes', max_length=20)),
                ('file', models.FileField(upload_to='subject_materials/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='reviews',
            field=models.ManyToManyField(through='subjects.SubjectRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.university'),
        ),
        migrations.AddField(
            model_name='degree',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.university'),
        ),
    ]
