# Generated by Django 4.2.2 on 2023-09-27 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 18, 54, 35, 362919)),
        ),
    ]
