# Generated by Django 4.2.2 on 2023-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
