# Generated by Django 4.2.2 on 2024-02-18 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subjectrating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 14, 30, 53, 641619)),
        ),
    ]
