# Generated by Django 4.2.2 on 2023-07-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='coordinator',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='language',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
