# Generated by Django 4.2.2 on 2024-02-19 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subjectrating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 15, 20, 59, 469482)),
        ),
    ]
