# Generated by Django 4.2.2 on 2023-07-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_degree_name_alter_subject_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='coordinator',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='language',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.TextField(max_length=10000),
        ),
    ]
