# Generated by Django 4.2.2 on 2023-09-09 15:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0006_subjectrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='reviews',
            field=models.ManyToManyField(through='subjects.SubjectRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectrating',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 17, 22, 15, 275506)),
        ),
    ]
