# Generated by Django 4.2.2 on 2023-09-19 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_alter_subjectrating_created_at_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 9, 49, 41, 523840)),
        ),
        migrations.CreateModel(
            name='SubjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('Apuntes', 'Apuntes'), ('Ejercicios', 'Ejercicios'), ('Examenes', 'Exámenes')], default='Apuntes', max_length=20)),
                ('file', models.FileField(upload_to='subject_materials/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
    ]
