# Generated by Django 4.2.2 on 2024-03-12 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_alter_subjectrating_created_at_subjectschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 11, 3, 49, 704448)),
        ),
    ]
