# Generated by Django 4.2.2 on 2024-03-26 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_dossier_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectindossier',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 12, 57, 11, 124319)),
        ),
    ]
