# Generated by Django 4.2.2 on 2024-03-26 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_alter_subjectindossier_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 19, 6, 14, 521709)),
        ),
        migrations.CreateModel(
            name='ExtraCurricularCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_curricular_credits', to='subjects.dossier')),
            ],
        ),
    ]
