# Generated by Django 4.2.2 on 2024-03-26 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0016_alter_subjectrating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 20, 17, 19, 897986)),
        ),
    ]
