# Generated by Django 4.2.2 on 2024-03-28 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0020_alter_subjectmaterial_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaterial',
            name='material_type',
            field=models.CharField(choices=[('Apuntes', 'Apuntes'), ('Ejercicios/Prácticas', 'Ejercicios/Prácticas'), ('Examenes', 'Exámenes')], default='Apuntes', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 10, 45, 19, 622448)),
        ),
    ]
