# Generated by Django 4.2.2 on 2024-02-18 13:30

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Piso')),
                ('door', models.CharField(blank=True, max_length=10, verbose_name='Letra')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='credits_passed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, choices=[('', 'No especificado'), ('UAM', 'Universidad Autónoma de Madrid'), ('UC3M', 'Universidad Carlos III de Madrid'), ('UAB', 'Universidad Autónoma de Barcelona')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='university_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, choices=[('', 'No especificado'), ('1', '1º'), ('2', '2º'), ('3', '3º'), ('4', '4º')], default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.address'),
        ),
    ]
