# Generated by Django 4.2.2 on 2024-02-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
    ]
