# Generated by Django 4.2.2 on 2024-03-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle'),
        ),
    ]
