# Generated by Django 4.2.2 on 2024-03-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
