# Generated by Django 4.2.2 on 2024-03-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_remove_profile_email_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_url',
            new_name='linkedin_url',
        ),
    ]
