# Generated by Django 4.2.2 on 2024-03-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_rename_facebook_url_profile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_expediente_public',
            field=models.BooleanField(default=False),
        ),
    ]
